# 微信相关配置
[weixin]

# 获取accessTokenAPI
accessTokenAPI = https://qyapi.weixin.qq.com/cgi-bin/gettoken

# 发送消息API
sendMessageAPIURL = https://qyapi.weixin.qq.com/cgi-bin/message/send

# corpID 公司或组织的ID
# corpID = xxxxx
corpID = xxx


# 报警应用的ID
# warningAppAgentID = 11111111
warningAppAgentID = 1000000

# 报警应用的密钥
# warningAppSecret = xxxxxxxxxxxx
warningAppSecret = xxx